### ISSUE TITLE
repository contains unrelated files

### ISSUE THREAD

**Issue by lsaffre** [miller2082/lino_polls#1]
The repository contains quite some files which seem to be there accidentally.

**Comment by miller2082** [comment]
Oh yes. Thanks!

The mistake I made was pushing to Github.

Seeing all the .pyc files in a repo is madening!

I didn't make a .gitignore file, which I learned when pushing myBigFatSite.

Now I need to clean up the repo.

**Comment by miller2082** [comment]
On local machine, ran git rm -f *.pyc *~.

then wrote .gitignore with the following content:

a (virtualenv for project which should stay in local machine)
*.DS_Store
*.pyc
__pycache__
*~
db.sqlite3      # Don't want this in Github or production environment.
/static
